<?php

	$id = "ten";
	$title = 'Pegasus Capital Group Newsletter vol. 3, "Sustainable Building Materials"';
	$subtitle = "Los Angeles, CA - October 2011";


	$body = <<<EOT
Sustainable Building Materials
In contrast to the stagnant broader building materials industry that has persisted since 2008, there has been robust activity in a key sub-sector: the green building materials industry. The growth in this industry has been driven by the evolution and adoption of new green building codes and standards.  As greater importance is placed on a building's entire life cycle, including the type of materials used, the green building materials industry is projected to grow faster than the broader building construction materials industry through 2015.  One of the main benefits of adapting to the new, more environmentally friendly manufacturing and construction practices is significant economic savings.  This comes from reduced energy usage, materials costs and water savings over the life of the buildings, as well as reduced costs of using recycled materials that can cut production costs by 2-10 times, according to some estimates.

Overview of Building Materials Industry
Building materials is a very large and diverse industry encompassing all types of materials used in construction, including steel, aluminum, concrete, glass, and wood, among many others.  The size of the US building materials supply industry, which First Research reported as $230 billion in its April 2011 report, displays the scope of the building materials industry size, which is not easily measured on the aggregate level.

In the United States, the building materials industry is still suffering from the economic recession with only minimal recovery.  An index that measures builders' sentiment for the building materials industry fell to 14 in September 2011, just one point above the lowest level in twelve months and only six points above the lowest level on record in 2009.  Builders are having a tough time constructing new homes and selling them for prices that cover costs, according to Bob Nielson, chairman of the National Association of Home Builders.  Commercial construction activity is also stagnating.  However, this is expected to reach the bottom soon, as indicated by the slowing rate of decline in contract award.  The Architecture Billings Index also showed potential growth in the commercial construction market, with a score of 51.4 in August 2011.  Scores above 50 indicate an increase in billings, and this is a leading indicator for construction spending over the next 6 to 9 months.

In contrast to the demand, the cost of construction materials has increased in 2011, which further decreases profitability for construction firms.  "Materials costs for construction have greatly outstripped the Consumer Price Index and even the overall Producer Price Index in the first four months of 2011," says Ken Simonson, chief economist for The Associated General Contractors of America.  Although the cost of raw materials like steel, diesel fuel, and copper are rising, contractors are continuing to work on projects for minimal price increases.  Unless they keep prices low, the contractors risk losing the entire job.  Overall, the price of construction materials is projected to be 5% to 6% higher in December 2011 than in December 2010, according to Simonson.

This increase in prices, along with the stagnating demand for new buildings, has not surprisingly had negative repercussions for the building materials industry.   Total construction spending since August 2010 has remained relatively flat, up just 0.9% in 12 months, according to the U.S. Census Bureau. While the Private sector portion of that figure has risen 5.6% in the 12 month period, the 6.3% decrease in Public sector spending nearly offsets the gain.  With budgets tightened at all levels of government, it is predicted that public spending will keep shrinking for years to come.  There is, however, expectation that development activity will increase gradually into 2012 for certain building types and industries, such as apartments, manufacturing, private hospitals, and warehouse and distribution projects.

Regarding new development projects, Richard Green, director of the Lusk Center for Real Estate at University of Southern California, believes that there won't be a demand for new buildings until 2014, except for specific purposes and locations.  Green stated that unless the US economy reaches pre-recession employment levels, there may not be much need for commercial real estate development.  To get to that level, there need to be seven million jobs created, and this will take about three years at the current pace of job growth.  "Outside of the most prestigious properties and locations, it's hard to see any recovery in office anytime soon."

Green Building Materials
Despite the overall industry outlook, there has been a significant boost for the building materials sector coming from an ongoing focus on green construction.  Governmental, regulatory and professional organizations are modifying and adopting a new range of green building codes and standards that place greater importance on all aspects of a building's lifecycle: where and how a building is built, the resources it consumes, how it affects the environment, and what materials are used.  For example, a key new trend has been greater use of recycled materials driven by the US Green Building Council's Leadership in Energy and Environmental Design (LEED) system. LEED is a voluntary rating system that rates a building's environmental impact in order to encourage greater sustainability.

The emphasis on green building materials has translated to a projected annual growth rate for the industry of 13% in five years, from $38.7 billion in 2010 to $71.1 billion in 2015.  This growth rate is slightly higher than that of the building construction expenditures projected over the same period, since green materials are expected to account for an increasing share of materials used.  The other key driver for demand will be the expected rebound in the construction market from 2010's low levels.  Some of the products enjoying growth rates of approximately 20%, (higher than the industry average) are water-efficient plumbing fixtures and fittings, energy-efficient lighting fixtures, permeable pavement, and concrete that features recycled content.   The U.S. is the second largest market for green materials, following Europe.

There are numerous companies working on innovative new building materials, such as DuPont, BASF, Ciba, and Calera. DuPont, which has shown a commitment to sustainability in its R&D processes, has a joint venture with Tate & Lyle to build one of the world's largest biomaterials facilities. This facility will convert corn sugar into Bio-PDO, a renewable ingredient that is used to make Dupont's Sorona polymer.  This polymer serves as a raw material for products such as carpet that provides an innovative benefit of permanent stain protection. Another new DuPont product is Sentryglas, which incorporates new interlayers that are stronger and stiffer than conventional materials to create a lighter, safe, and more structurally sound glass. Sentryglas can withstand greater loads and higher threat levels, such as hurricanes, than conventional glass.  Other innovations include phase-change materials that address thermal loss from homes to make them more energy-efficient. Companies such as BASF and Ciba are working on these technologies to incorporate phase-change materials into window construction.

Calera, another company in the green building materials industry, is developing a new cement manufacturing process that reduces the amount of CO2 released by power plants.  The firm utilizes a process that puts CO2 (an emission gas) in contact with water from various sources so that the minerals in the water bind to the gas.  The byproducts of this process are mineral carbonates and bicarbonates that have a number of construction applications, such as cement.  Another beneficial output is water that is more purified because the salts and minerals have been removed through the carbon dioxide capturing process.  Calera has built a demonstration plant in California that is capable of capturing 30,000 tons of CO2 per year, equivalent to the CO2 output of a 10MWe natural gas power plant.

This type of new product development is likely to continue as building requirements are amended further to minimize the impact of construction on the environment.  This translates into projects that further cut emissions and energy usage, which is leading to the development of "smart" buildings that can react both to energy usage and to the needs of occupants. However, while new products may bring promise, their application or use may be curtailed by the stringent requirements of local planning offices for residential construction.  These planning organizations have narrow specifications for acceptable building materials, so it can be difficult for new materials to be approved for use by these groups.

Past and Ongoing Sustainability and Green Initiatives with Building Products: Steel
The steel industry, which produces one of the most prevalent building materials in the world, has been increasing efficiency and reducing its carbon footprint in steel production for decades.  There is a very high recycling rate for steel, 93.3% for structural steel, and it is the most recycled material - more than all other materials combined (as measured in tons).  U.S. steel companies have been especially vigilant in reducing energy use and carbon dioxide emissions, as demonstrated by the lowest energy intensity per ton of steel produced compared to other nations.  The United States also ranked second-lowest in terms of carbon dioxide emissions per ton of steel produced, behind South Korea.

There is increased recognition among architects that steel is an attractive building material for its important environmental qualities, especially its recycled content and high reclamation rate (a measure of how often a product is recycled at the end of its life).  Using old steel products and other forms of ferrous scrap to produce new steel lowers steelmaking costs and reduces the energy used by 75%.  In addition, the steel industry has been cutting the amount of energy used in the steel production process, reducing energy intensity by 30% from 1990.  With these improvements, steel construction materials currently meet the green construction criteria established by the LEED rating system.  The voluntary LEED system established by the U.S. government has been instrumental in the promotion of recycled materials, just like in the steel industry, and will continue to promote greater sustainability.

One form of steel that is useful for satisfying sustainability requirements is cold-formed steel (CFS).  Compared to wood-based building projects, CFS construction reduces the waste produced at a building site.  Many high performance buildings (another term for green buildings that are environmentally responsible and resource-efficient throughout their life-cycle) have been constructed with CFS framing.  The advantages of using CFS include its consistent recycled content as well as the ability to recycle it repeatedly, making future demolition and reuse more appealing.

Next Steps for Steel
Despite the improvements mentioned above, American steel industry experts emphasize the need for investment in new manufacturing procedures that go beyond incremental improvements.  Wide-scale application of new technologies that could disrupt current processes, such as carbon sequestration, remain unproven and need "significant research and development investments," according to Thomas Gibson, President and CEO of the American Iron and Steel Institute.  He called for larger commitments from the federal government for additional research, similar to those made by European and Asian governments.  This would help alleviate the pressure on the U.S. steel industry to balance the extra costs of greener manufacturing processes with competition from other companies and/or countries that are not required to comply with U.S. specific laws.

Past and Ongoing Sustainability and Green Initiatives with Building Products: Aluminum
The world's leading producer of aluminum, Alcoa, has also been improving its aluminum product line to be more environmentally friendly. The company recently introduced a coil-coated aluminum panel called Reynobond with EcoClean that cleans itself and the air around it. It aids in the decomposition of smog and other pollutants that cling to the panel surfaces. According to Alcoa, 10,000 square feet of the new panel has the equivalent air cleansing power of about 80 trees, offsetting the pollution of four cars each day.

When exposed to sunlight, the innovative Reynobond panel acts as a catalyst to break down pollutants, both on its surface and the surrounding air, into harmless matter. The panel's coating, which is super-hydrophilic, washes away the harmless particles when it comes in contact with rain or humidity. Thus, these panels not only help keep the environment clean, but also yield savings on maintenance costs.

Prefab Commercial Buildings: Another Cost and Material Saving Concept
Along with the new developments in building materials, there appears to be a resurgence of previously utilized cost efficient trends, such as prefab commercial buildings.  The prefab market currently accounts for only 1 percent of the commercial building market, mostly limited to schools, hospitals, dormitories or retail stores.   However, with the greater focus on materials conservation and reuse, as well as lower costs, modular construction is getting more attention.
A modularly-constructed building uses the same materials as a traditional one, but is made in a factory.  In this controlled environment, buildings can be constructed more quickly with less waste.  Nearly all contemporary buildings incorporate some prefabrication, with facades largely constructed off-site and windows and doors standardized.  A developer can save up to 20 percent in construction costs with modular building, primarily from lower labor costs.  The time saved is significant as well, since buildings can be constructed faster in a factory, with greater efficiency and a better coordinated production schedule.  However, prefab does have the limitation of unfamiliarity for most architects, developers and contractors who are hesitant to take risks in an unstable market.  A fully prefab building also requires every decision about the building be made before construction begins.  The third issue is that the building must be designed so it can fit in containers that meet Federal Highway Administration regulations.  If these issues can be overcome, the lower cost and faster production time of prefab building may aid in the recovery of the construction market.

Conclusion
As the construction and buildings materials industries continue to seek recovery from the economic recession, there appears to be hope in the rapid growth of the green building materials sub-sector. This growth satisfies both customer demand for environmentally sustainable products, as well as new governmental guidelines. Furthermore, utilizing new materials and greener processes can provide economic benefits to those who adapt.  Innovations in commonly used materials such as steel and aluminum, along with the development of brand new materials, make this an evolving and exciting area of growth.
EOT;
$body = nl2p($body);

?>